version: '3.7'

services:
  app:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: .
    volumes:
      - .:/code
    environment:
      POSTGRES_PASSWORD: password
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
     - 5432:5432
